apiVersion: v1
kind: Service
metadata:
  labels:
    service: vanilla-py-web
    app: vanilla-py-web
  name: vanilla-py-web
spec:
  ports:
  - port: 9000 # host
    protocol: TCP
    targetPort: 5000 # container
  selector:
    service: vanilla-py-web
    app: vanilla-py-web
status: {}

